hostname = %APPEND% api.bilibili.com, app.bilibili.com

# rewrite
^https?://app\.bilibili\.com/x/resource/top/activity\?access_key url reject-200
^https?://app\.bilibili\.com/x/v\d/(search/(defaultword|square)) url reject-200
^https?://api\.bilibili\.com/x/v\d/dm/ad url reject-200

# script
^https?://app\.bilibili\.com/x/v\d/splash/list url script-response-body https://raw.githubusercontent.com/srk24/profile/master/bilibili_splash.js
^https?://app\.bilibili\.com/x/resource/show/tab\?access_key url script-response-body https://raw.githubusercontent.com/srk24/profile/master/bilibili_all.js
^https?://app\.bilibili\.com/x/v\d/feed/index\?access_key url script-response-body https://raw.githubusercontent.com/srk24/profile/master/bilibili_all.js
^https?://app\.bilibili\.com/x/v\d/account/mine\?access_key url script-response-body https://raw.githubusercontent.com/srk24/profile/master/bilibili_all.js
^https?://app\.bilibili\.com/x/v\d/view\?access_key url script-response-body https://raw.githubusercontent.com/srk24/profile/master/bilibili_all.js
